{% set version = "2.4-6" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-filehash
  version: {{ version|replace("-", "_") }}

source:
  fn: filehash_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/filehash_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/filehash/filehash_{{ version }}.tar.gz

  sha256: 558b446ba354c6fa88f694e8d6d068f999d1e7b626164eb2aeacccbb0dee81b1

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                      # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ stdlib("c") }}          # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
  host:
    - r-base
    - r-digest
  run:
    - r-base
    - r-digest

test:
  commands:
    - $R -e "library('filehash')"  # [not win]
    - "\"%R%\" -e \"library('filehash')\""  # [win]

about:
  home: https://cran.r-project.org/package=filehash
  dev_url: https://github.com/rdpeng/filehash
  license: GPL-2.0-or-later
  summary: Implements a simple key-value style database where character string keys are associated with data values that are stored on the disk. A simple interface is provided for inserting, retrieving, and deleting data from the database. Utilities are provided that allow 'filehash' databases to be treated much like environments
    and lists are already used in R. These utilities are provided to encourage interactive and exploratory analysis on large datasets. Three different file formats for representing the database are currently available and new formats can easily be incorporated by third parties for use in the 'filehash' framework.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
