travis:
  secure:
    BINSTAR_TOKEN: VIfBV/u51V/juz7pOFm6yl+ljpj4BwZbJBRZWlq5RktQhsGJ8ZQ285J7cySrlcdJMHNVxclCEQNLshVo0oJOEX2lIDZux460CtAhNpkSX6mNbS4pSFX5KIUjQZgwDdKkUaJbOnjH8t47cB7yW3qkk6EpG/z1LJ8b9mnRP9Iw+A6SoKhuO08K5FQ7UzSnQ+xZmIqqFw6wWK1QNE14Hwcg6Opj1T+OQaghxSsIVnRgrk9NKlss4FYGso53kHr7XXIcLN5SR+sUq0MfmXuTK5ArWNugJEK8WF8TJ2vNyLbPBLc3C5VczNdb/NgLjVpdq+m2Y3tPboZUDb8L653JyBXYbIEPGBuRGU4qZ5plpq3FLyq8re2gyYsCIFJJTm3dUHP9kgW7LTPKTwrAUj309/ttJJhxB27wod4azi0LwKGofH1Ho73voivlNrJ8/G/02fKwgB6dSQqIi74t/7/Fa5bmJ9Iga8VVwpstO/HPS9SbvwjDOszTKVSVRzbTgAVaOLg50McvzjmlQQtFjEXAWkmUb1Hxxg268PumOO4ABKMZgJo+5ODLCkRL+MUIyPIEg4P5ArLUj6ZskTUhD12L77LcvaI14kPHYG4jmdj3Jg7ahaWMVeuTyPv3awM0gv/2HXdjNQxpM4/3HAU2vjo+utS2bQ2N9pTn908GEvKr0PwmWL0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
