travis:
  secure:
    BINSTAR_TOKEN: axrIZBcOdU5US4PVIDHOmbongCygpvsk+8+6JIKf+TJfspB3zNIr0KSVQ+MuHmMGzKD7z1Iy+ykKQ6OCL3wWZUdngt5JRHLNIyTmxFVEMPAYOesQqwnyR0kDqe9tVi4fl9K30/mt6rbnYsaFzieKRBjfa6t9o1HtfAudv64bGArbaoC+5TkKMPtysa9Du/SORvAAXKBwlrrTh9NflHXop586Nd2Wig4p3QnSPCqQoWsdI7ZalXFuS77XHVhRM0U9rtIbRfWekWMMVZC+VGhJFBvCmUHnbsxxOKRmeA0IPVyYbuZ23Kwd/oWtf+c43KLM/gSBOW5Zyz02HT2082zOoKMvLv20zB26hFfmwKg7ASY+mMFVWQNUk4u7oJJl7uyquZiM511lm0M+8GhQ+tl0g5jXNqn4cFx26T3lCb8JC4YWwXiJspz0ZrLqYbcGOVeycaP0XwXqYTOMV57lZQQBrm4YKGyNB1N49jjHenhe6j1GNN6Vh5cWay736YK6vjXcGAZHtPaFv6WMrVdHkq0RInkwswx3VmDj9qem6Rb4v1TZGtS69Y3cCW5lArJNSSdjw1iiAYPyB7tD9RfS6/vNN1LC9JpymdQT0Qd8moNJeCOnzpkIx+ILCHIs0oYQhtru1EGIbdj2Mi3xGGwXtPFRx4aoG6I9wdRqBnWIxq1I0u0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
