travis:
  secure:
    BINSTAR_TOKEN: cNVfWpFETik+WDpvcDXBFJEi07WLkGc1COfoWg0bHoiDS11l2gTOMMe/Vxa34VCGoqvUgFgCzeuewwNr9uUapan0QXVTVdrYRwhXT4IGn4MGHRuo0ULriahDNTzrRFO0R4XaEiOyF70W+ur0YDO9IynrcpZHk+bBi0Wk5iHBzey3cqSXLSQQOXkruk0fP3kGT/JFnsnl1T7lZ8u6DqxJV0GOblMiEwz+F9U2D/9whTu2+RM545vwHJbkLpVnzQEvYWYhVOkUArZLQT2AaRZNFvTDwXShv0PSWI+ypqGYT94sCLo6JAFRvV69+2fZZpytMNLPgyPPjSqaMtsF+s+KnUurgRSGow6uoYd8pzFUIUYsOia3gbs//3JHmirjpUY87EvUIuZjUXw9FOmC/bL83E8EES4G4EOC6LOGmf21/q7wBGJ/OXc3COr45bKt/QT5tTWVx5qA132l8VzUdYTInTVULON5rvUyLm6YmmV2DMxc0tRsvPkQGBSEXZBaFNiQXs0VshufDldADOtBYNOB5RyWHFiFC0DmdoFWyffxY2jpSr60dSyoktgygKIdxEFhfTh2/tWUhriHPX6iSUgE2LVyEqkOufxz3aLZAFJj1H9Aq8n0p+/aSDkc7dY/Ph+VUbhySKkAFeypGoBeiuRfsdkvQsRa1eOAYylFrjcjUjs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
