appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: NXHwb0Hl1T07sC9hj+T0sKMr5g1zf131V6n9G6rYiPbz/HZAn1PqbvV1SkzKFZ/cFpSneONm0+UdwKDdzQMVVnXztz4jf+r3lbdRNN194OXY0K0nn1Cl/DHpJ9B109zQzp+BIaJ88YUqt/s1IfRnepFCVZLIOWL2IGYwsniqAHDEi3PpTB9Jt5NU/nbBvo5WKASUY0S9R8FDxRWKCym//W6mS0oOpMYFarNCnGRl274WZeQAOiy4UpTn1DQOv66MyQcqKc298Ev3UH0E5giWMV6ff7+0F10ZD4oCcoPzVfATtShPDePbb2BfDeYWjIm2XxigQEqALj6+XyD7DCUoQ1aWzWk0tXjju8Gbd8AsOiew9Z14O4VqcfhUQBW63giq4gIhrKxgA95AIeUmrKgM8TPeTua9LS9qPAbeBkrxS/wO/jMPXEveiul4qadHJx6j89TEnXUEiA7LewDyORniQ5P8YeqFE7ma54MtYNA+ZSDmxm6zn9/QN2XXwxHrIAYm0olk6wdzMYL4x0Iv0WAJoNUoD8muPJr11WF9+n7zJAiuI1UxQCjY95+HgK3QAdBuGyDWGfK8BqZNzfZNobkEkmhgCd3NS84aUvpeTwkhdgYBlLssl1hiGp8np3eM2zwa4ovYCBxpMochuaifTYM6eqm7xyk3zHtZCirOPxyWlGs=
